### PR TITLE
update version to v2

### PR DESCRIPTION
**Pull request by jessfraz**
Signed-off-by: Jessica Frazelle jess@docker.com

/me does not know what the other scripts do :(

### CODE REVIEW

**Comment by tianon** [comment]
Heh, this one has upstream artifacts, so it's messy...  :sob:

**Comment by tianon** [comment]
Oh man, I'm a dumbass: https://packages.debian.org/experimental/golang-dbus-dev

:dizzy_face:

So, uh, this was good practice? :disappointed:

**Comment by jessfraz** [comment]
hahha nice

**Pull request closed without merging**
